name: Publish docker openjdk images

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  generating_dockerfiles:

    name: Generating dockerfiles
    runs-on: ubuntu-20.04
    steps:

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Run bash script
        shell: bash
        run: |
          chmod +x ./render.sh
          ./render.sh
      - name : Upload dockerfiles
        uses: actions/upload-artifact@v2
        with:
          name: dockerfiles
          path: ./dockerfiles

  hadolint:

    name: Hadolint
    needs: generating_dockerfiles
    runs-on: ubuntu-20.04
    steps:

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Download dockerfiles
        uses: actions/download-artifact@v2
        with:
          name: dockerfiles
          path: ./dockerfiles

      - name: Lint All Dockerfile
        run: make hadolint

  push_to_docker_hub:

    name: Login to Docker Hub
    needs: hadolint
    runs-on: ubuntu-20.04
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Download dockerfiles
        uses: actions/download-artifact@v2
        with:
          name: dockerfiles
          path: ./dockerfiles

      - name: Docker login
        run: make login
        
      - name: Build the Docker image
        shell: bash
        run: |
          for openjdk in $(ls ./dockerfiles); do
            docker build --tag ${DOCKER_USERNAME}/${openjdk}:0.1 ./dockerfiles/${openjdk} &
          done
          wait

      - name: Docker Push
        shell: bash
        run: |
          for openjdk in $(ls ./dockerfiles); do
            docker push ${DOCKER_USERNAME}/${openjdk}:0.1 &
          done
          wait