name: Publish docker openjdk images

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  generating_dockerfiles:

    name: Generating dockerfiles
    runs-on: ubuntu-20.04
    steps:

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Generating dockerfiles
        shell: bash
        run: |
          chmod +x ./scripts.sh
          ./scripts.sh generate_dockerfiles

      - name : Upload dockerfiles
        uses: actions/upload-artifact@v2
        with:
          name: dockerfiles
          path: ./dockerfiles

  hadolint:

    name: Hadolint
    needs: generating_dockerfiles
    runs-on: ubuntu-20.04
    steps:

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Download dockerfiles
        uses: actions/download-artifact@v2
        with:
          name: dockerfiles
          path: ./dockerfiles

      - name: Lint All Dockerfile
        shell: bash
        run: ./scripts.sh hadolint

  push_to_docker_hub:

    name: Login to Docker Hub
    needs: hadolint
    runs-on: ubuntu-20.04
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Download dockerfiles
        uses: actions/download-artifact@v2
        with:
          name: dockerfiles
          path: ./dockerfiles

      - name: Docker login
        shell: bash
        run: ./scripts.sh docker_login
        
      - name: Build the Docker image
        shell: bash
        run: ./scripts.sh docker_pull

      - name: Docker Push
        shell: bash
        run: ./scripts.sh docker_push